<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUwTZBmm\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUwTZBmm/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUwTZBmm.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUwTZBmm\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUwTZBmm\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'UwTZBmm',
    'container.build_id' => 'c1a67dd1',
    'container.build_time' => 1546890046,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUwTZBmm');
